name: HubParkour
main: org.ayosynk.hubparkour.HubParkourPlugin
version: 0.1.0
api-version: 1.20
author: ayosynk
softdepend: [PlaceholderAPI, FancyHolograms]
commands:
  parkour:
    description: Hub parkour management.
    usage: /parkour
    permission: hubparkour.admin
permissions:
  hubparkour.admin:
    default: op
